server:
  # https://docs.spring.io/spring-boot/docs/1.5.7.RELEASE/reference/htmlsingle/#howto-use-tomcat-behind-a-proxy-server
  use-forward-headers: true
  servlet:
    session:
      persistent: true
      # https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-
      timeout: PT2H

spring:
  application:
    name: blog

  profiles:
    active: development
    include: assets

  jpa:
    database: postgresql
    show-sql: true
    open-in-view: true

    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

  session:
    # https://github.com/spring-projects/spring-session/blob/master/docs/src/docs/asciidoc/guides/boot-redis.adoc
    store-type: redis
    redis:
      namespace: ${spring.application.name}

  freemarker:
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    allowSessionOverride: true
    settings:
      incompatible_improvements: 2.3.26
      # Required for ?url built in string util
      # http://freemarker.org/docs/ref_builtins_string.html#ref_builtin_url
      output_encoding: UTF-8
      # Required to enable auto escaping
      # http://freemarker.org/docs/dgui_misc_autoescaping.html
      output_format: HTMLOutputFormat
      auto_import: >
        frontend/layout/layout.ftl as layout,
        admin/layout/layout.ftl as adminLayout,
        helper/asset-helper.ftl as assetHelper

  devtools:
    restart:
      additional-exclude: freemarker_implicit.ftl

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.hibernate: info

assets:
  cdn:
    enabled: true
    provider: cdnjs

  broccoli:
    enabled: false
    host: localhost
    port: 4200

blog:
  host: http://sayef.tech
  title: "Sayef's Tech Blog"
  disqus:
    enabled: true
    shortname: sayef-tech

uploads:
  storage-dir: uploads

cv:
  url: "https://www.visualcv.com/sayef"
